### ISSUE TITLE
Can’t update plugin

### ISSUE THREAD

**Issue by ericdhkim** [homebridge/homebridge-config-ui-x#1562]
### Describe The Bug

When I try to update the myQ plugin via the Homebridge web UI, I get an error. I'm able to update other plugins, homebridge UI, as well as the Raspberry Pi without issue, but am seeing this error with only this plugin update. I see the below error:
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-myq@3.2.0

npm ERR! Cannot read properties of undefined (reading 'isStream')

npm ERR! A complete log of this run can be found in: /home/homebridge/.npm/_logs/2023-08-22T04_23_04_678Z-debug-0.log

### Logs

```text
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.1
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 8ms
8 warn config global-style This option has been deprecated in favor of --install-strategy=shallow
9 timing config:load:env Completed in 2ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/homebridge/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 3ms
16 timing config:load Completed in 26ms
17 timing npm:load:configload Completed in 26ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install homebridge-myq@3.2.0
21 verbose argv "install" "--global" "homebridge-myq@3.2.0"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 10ms
24 timing npm:load:display Completed in 13ms
```

### Homebridge UI Version

4.50.5

### Homebridge Version

1.6.1

### Node.js Version

18.17.1

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Hi @ericdhkim 

Can you use the terminal within the homebridge ui to run this command (to install/update the plugin)

```
sudo npm install -g homebridge-myq@3.2.0
```

and try and post the full output of what it shows there?

Ta

**Comment by bwp91** [comment]
Edit - added sudo to the command

**Comment by ericdhkim** [comment]
I got the same error and same error log (exact same error code about isSteeam)

**Comment by bwp91** [comment]
@ericdhkim 

dunno if you found a solution to this by now.

I wonder if a node update would help.

Can you run this from the homebridge terminal?

```
sudo hb-service update-node 18.18.1
```

and once this finishes (and homebridge restarts etc) trying to update the plugin may succeed?

**Comment by ericdhkim** [comment]
Yeah so I did update to 18.18.1 and even uninstalled the plugin and tried to install again from the UI but getting the same error

**Comment by aliry** [comment]
have the same problem.
when trying to update from UI it stops downloading around 26%.
Using the terminal also stops downloading the package.
<img width="1107" alt="image" src="https://github.com/homebridge/homebridge-config-ui-x/assets/6610388/4326f124-7f19-4c22-a5ac-5f97bbd0519d">

**Comment by aliry** [comment]
Had similar issue. 
`sudo reboot` fixed the issue

**Comment by ericdhkim** [comment]
I was in my homebridge ui today and had issues updating to 4.51.0 (which I eventually fixed with rebuild command) when I noticed that my node version actually wasn’t on 18.18.1. When I tried the command again, I got an error that it couldn’t update
![IMG_2403](https://github.com/homebridge/homebridge-config-ui-x/assets/61293059/9b2ca906-0fb6-4639-b545-37da27cc8ac8)

**Comment by Lightoar** [comment]
I also am getting the same error when trying to update. 

Ubuntu 22.04 
Homebridge v1.6.1
Homebridge UI v4.51.2
nodejs v20.5.1 

Was getting the same error on nodejs v18 before updating (updating didn't fix issue).

Let me know if I can provide more information to assist.

**Comment by Taureans** [comment]
> I also am getting the same error when trying to update.
> 
> Ubuntu 22.04 Homebridge v1.6.1 Homebridge UI v4.51.2 nodejs v20.5.1
> 
> Was getting the same error on nodejs v18 before updating (updating didn't fix issue).
> 
> Let me know if I can provide more information to assist.

Hi, were you able to resolve this issue?
Thank you.
